[[constraint]]
  name = "github.com/devopsfaith/krakend"
  version = "0.7.0"

[[constraint]]
  name = "github.com/devopsfaith/krakend-metrics"
  version = "0.8.0"

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "1.7.3"

[prune]
  go-tests = true
  unused-packages = true
